### ISSUE TITLE
Using `logging.debug()` and friends impacts downstream users

### ISSUE THREAD

**Issue by peterschutt** [kuimono/openapi-schema-pydantic#19]
We had a user open this issue:

https://github.com/starlite-api/starlite/issues/144

… and traced the cause back to here.

From docs for `logging.debug()`:

> This function (as well as info(), warning(), error() and critical()) will call basicConfig() if the root logger doesn’t have any handler attached.

So instead of `logging.info(…)`, it is better to instantiate a named logger for your library, e.g.:

```python
import logging

logger = logging.getLogger(__name__)
logger.debug(…)
```

Would you accept a PR?

**Comment by kuimono** [comment]
Yes please submit a PR if possible.
