### ISSUE TITLE
How to generate parameters from pydantic schema?

### ISSUE THREAD

**Issue by manycoding** [kuimono/openapi-schema-pydantic#23]
https://swagger.io/docs/specification/describing-parameters/

**Comment by kuimono** [comment]
The parameters should have been defined under the `Operation` object:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operationObject

**Comment by manycoding** [comment]
Thanks, I meant how to do it with this sdk. Seems this feature is not implemented.
