### ISSUE TITLE
`discriminator` attribute conflicts with internal pydantic Field attribute

### ISSUE THREAD

**Issue by tommilligan** [kuimono/openapi-schema-pydantic#8]
Versions:

```bash
$ pip list | rg pydantic
openapi-schema-pydantic                1.2.1
pydantic                               1.9.0
```

Prior to pydantic 1.9.0, `discriminator` was not a reserved attribute in the `pydantic.Field` class. This meant the following definition was valid:

```py
from typing import Literal, Union

from openapi_schema_pydantic import Discriminator
from pydantic import BaseModel, Field


class DataAModel(BaseModel):
    kind: Literal["a"]


class DataBModel(BaseModel):
    kind: Literal["b"]


class RequestModel(BaseModel):
    data: Union[DataAModel, DataBModel] = Field(
        ...,
        discriminator=Discriminator(
            propertyName="kind",
            mapping={
                "a": "#/components/schemas/DataAModel",
                "b": "#/components/schemas/DataBModel",
            },
        ),
    )
```

Now that  `discriminator` is reserved, this results in a TypeError on defining the class:

```bash
python repro.py
Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    class RequestModel(BaseModel):
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/main.py", line 204, in __new__
    fields[ann_name] = ModelField.infer(
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/fields.py", line 527, in infer
    return cls(
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/fields.py", line 444, in __init__
    self.prepare()
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/fields.py", line 577, in prepare
    self._type_analysis()
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/fields.py", line 684, in _type_analysis
    self.prepare_discriminated_union_sub_fields()
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/fields.py", line 824, in prepare_discriminated_union_sub_fields
    alias, discriminator_values = get_discriminator_alias_and_values(
  File "/home/tom/r/env/lib/python3.8/site-packages/pydantic/utils.py", line 733, in get_discriminator_alias_and_values
    t_discriminator_type = tp.__fields__[discriminator_key].type_
TypeError: unhashable type: 'Discriminator'
```

Pydantic now expects `discriminator` to be a string, specifying the field that contains the discriminating value (in this case, `kind`). See the pydantic documentation on [discriminated unions](https://pydantic-docs.helpmanual.io/usage/types/#discriminated-unions-aka-tagged-unions).

Would you accept a PR that adds an alias for this field, to still allow it to be loaded from the field definition - say, `discriminatorMapping`?

**Comment by kuimono** [comment]
As you have mentioned, the expected value of `discriminator` in `pydantic.Field` should be a string - it is not expected to use the `Discriminator` object. It is part of the pydantic library feature, and nothing we can do about it.

Besides, the expected usage of `Discriminator` object is under the (JSON) `Schema` object.

**Comment by tommilligan** [comment]
> As you have mentioned, the expected value of `discriminator` in `pydantic.Field` should be a string - it is not expected to use the `Discriminator` object. It is part of the pydantic library feature, and nothing we can do about it.

Ageed. My point was more that, having upgraded to the latest `pydantic` version, we can no longer use openapi_schema_pydantic's `Discriminator` in this way to generate our openapi schema.

My suggestion would be to alias this field as we already do for other reserved keywords, such as `if`, `else` and `not`. This would I think allow us to still configure discriminator to produce a JSONSchema, while not conflicting with pydantic's other features.

Something like:

```python
from typing import Literal, Union

from openapi_schema_pydantic import Discriminator
from pydantic import BaseModel, Field


class DataAModel(BaseModel):
    kind: Literal["a"]


class DataBModel(BaseModel):
    kind: Literal["b"]


class RequestModel(BaseModel):
    data: Union[DataAModel, DataBModel] = Field(
        ...,
        # this is a pydantic specific feature, unrelated to openapi
        discriminator="kind",
        # this will be output in the JSONSchema as "discriminator"
        discriminator_mapping=Discriminator(
            propertyName="kind",
            mapping={
                "a": "#/components/schemas/DataAModel",
                "b": "#/components/schemas/DataBModel",
            },
        ),
    )
```

ref an existing alias: https://github.com/kuimono/openapi-schema-pydantic/blob/523fcf75ad188593dc5979d10084a86a83938eb5/openapi_schema_pydantic/v3/v3_1_0/schema.py#L589

> Besides, the expected usage of `Discriminator` object is under the (JSON) `Schema` object.

I'm not sure what you mean by this - are you saying we shouldn't be using the `discriminator` keyword in this way on a `Field`?

**Comment by kuimono** [comment]
> are you saying we shouldn't be using the `discriminator` keyword in this way on a `Field`?

Yes, you should just use string value in `Field`, as described in pydantic documentation.
Then the `RequestModel` can generate the JSON schema as we expected.

I have made the examples in the test case. See if it could help:
https://github.com/kuimono/openapi-schema-pydantic/blob/master/tests/util/test_pydantic_field.py#L48

**Comment by tommilligan** [comment]
Thank you very much - I see your test examples and they make sense, and I have verified I can get a minimal example working locally for me as well.

I'll investigate our specific case and see why it isn't behaving as desired. Thanks!
